version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-lc
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker_lc
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    
  api:
    image: node:latest
    container_name: api-lubycash
    restart: unless-stopped
    volumes:
      - .:/API_LubyCash
    ports:
      - "3333:3333"
    depends_on:
      - db-api
    command: node ace serve --watch

  db-api:
    image: mysql:latest
    container_name: db-lubycash
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "3305:3305"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: lubycash-api

  ms-approve:
    image: node:latest
    container_name: ms-approve
    restart: unless-stopped
    volumes:
      - .:/MS_APPROVE
    ports:
      - "3334:3334"
    depends_on:
      - db-ms
    command: node ace serve --watch

  db-ms:
    image: mysql:latest
    container_name: db-approve
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - "3307:3307"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: ms-approve
  
  ms-email:
    image: node:latest
    container_name: ms-email
    restart: unless-stopped
    volumes:
      - .:/MS_EMAILS
    ports:
      - "3335:3335"
    depends_on:
      - ms-approve
    command: node ace serve --watch